# Generated by Django 5.0.2 on 2024-07-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_book_photo_author_alter_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='photo_author',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='photo_book',
            new_name='photo',
        ),
    ]
