# Generated by Django 5.0.2 on 2024-07-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_rename_photo_author_book_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='photo_author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='photo',
            new_name='photo_book',
        ),
    ]
