# Generated by Django 5.0.2 on 2024-07-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_rename_image_book_photo_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_rentaln',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
