# Generated by Django 5.0.2 on 2024-07-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_book_total_rentaln'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='total_rentaln',
            new_name='total_rental',
        ),
    ]
